version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '8000:8000'
      - '8080:8080'
    container_name: dynamodb_localstack
    environment:
      SERVICES: dynamodb:8000 # overriding default port of 4569 with 8000
      DATA_DIR: '/tmp/localstack/data'
